-- =============================================================================
-- DEPLOY SEMANTIC VIEWS FROM GIT REPOSITORY
-- =============================================================================
-- Usage: Run after pushing changes to GitHub.
--
-- IMPORTANT: The deploy/ artefacts are auto-generated by:
--   python scripts/build_deploy.py
--
-- Semantic view YAML does NOT include custom_instructions (Snowflake
-- Semantic Views require AI instructions via SQL clauses, not YAML).
-- Custom instructions are set in a separate step after the YAML deploy.
--
-- Do NOT edit the deploy/ files directly — edit instruction modules
-- under instructions/ and semantic view definitions under semantic_views/.
--
-- Repository: https://github.com/WaynezWorld/insulintel-semantic-models
-- =============================================================================

-- Step 1: Fetch latest changes from GitHub
ALTER GIT REPOSITORY DB_INSULINTEL.SCH_SEMANTIC.REPO_SEMANTIC_MODELS FETCH;

-- Step 2: List files to verify sync
LIST @DB_INSULINTEL.SCH_SEMANTIC.REPO_SEMANTIC_MODELS/branches/main/;

-- Step 3: Deploy SEM_NHANES (base YAML)
SELECT 'Deploying SEM_NHANES...' AS status;
CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML(
  'DB_INSULINTEL.SCH_SEMANTIC',
  (SELECT $1 FROM @DB_INSULINTEL.SCH_SEMANTIC.REPO_SEMANTIC_MODELS/branches/main/deploy/sem_nhanes.yaml (FILE_FORMAT => 'DB_INSULINTEL.SCH_SEMANTIC.FF_YAML'))
);

-- Step 4: Deploy SEM_INSULINTEL (base YAML)
SELECT 'Deploying SEM_INSULINTEL...' AS status;
CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML(
  'DB_INSULINTEL.SCH_SEMANTIC',
  (SELECT $1 FROM @DB_INSULINTEL.SCH_SEMANTIC.REPO_SEMANTIC_MODELS/branches/main/deploy/sem_insulintel.yaml (FILE_FORMAT => 'DB_INSULINTEL.SCH_SEMANTIC.FF_YAML'))
);

-- Step 5: Deploy SEM_ACTIVITY (base YAML)
SELECT 'Deploying SEM_ACTIVITY...' AS status;
CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML(
  'DB_INSULINTEL.SCH_SEMANTIC',
  (SELECT $1 FROM @DB_INSULINTEL.SCH_SEMANTIC.REPO_SEMANTIC_MODELS/branches/main/deploy/sem_activity.yaml (FILE_FORMAT => 'DB_INSULINTEL.SCH_SEMANTIC.FF_YAML'))
);

-- Step 6: Set AI custom instructions (sql_generation + question_categorization)
-- Snowflake Semantic Views require AI instructions *after* YAML deploy,
-- via AI_SQL_GENERATION / AI_QUESTION_CATEGORIZATION on CREATE OR REPLACE.
EXECUTE IMMEDIATE FROM @DB_INSULINTEL.SCH_SEMANTIC.REPO_SEMANTIC_MODELS/branches/main/deploy/set_custom_instructions.sql;

-- Step 7: Verification
SELECT 'Deployment complete. Verifying...' AS status;
SHOW SEMANTIC VIEWS IN SCHEMA DB_INSULINTEL.SCH_SEMANTIC;
